### ISSUE TITLE
Cenário 4 - Crédito em poupança

### ISSUE THREAD

**Issue by adelinosegundo** [adelinosegundo/gcm-bank#10]
Funcionalidade de crédito em poupança.

<b>Solicitado por: Cliente Z</b>

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO: VALIDADO</b>

Prioridade resultante: Média
Impacto: Médio

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO DE CUSTO/BENEFÍCIO: VALIDADO</b>

**Comment by wendellpbarreto** [comment]
<b>DOCUMENTAÇÃO</b>

Prazo: 20 dias

*documentação*

Desenvolvedor: @adelinosegundo

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO DO CONTROLE DE QUALIDADE: VALIDADO</b>

**Comment by wendellpbarreto** [comment]
<b> RESULTADO DA ACEITAÇÃO DO CLIENTE: ACEITO</b>

Interessados: Cliente Z
