### ISSUE TITLE
Cenário 5 - Aprimoramento da operação de crédito

### ISSUE THREAD

**Issue by adelinosegundo** [adelinosegundo/gcm-bank#11]
Inclusão da seguinte mensagem ao efetuar a operação de crédito em poupança: “Crédito no valor XX para a conta YY realizado com sucesso”.

<b>Solicitado por: Cliente C</b>

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO: VALIDADO</b>

Prioridade resultante: Média
Impacto: Médio

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO DO COMITÊ DE CONTROLE DE MUDANÇAS: VALIDADO</b>

**Comment by wendellpbarreto** [comment]
<b>DOCUMENTAÇÃO</b>

Prazo: 35 dias

*documentação*

Desenvolvedor: @adelinosegundo

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO DO CONTROLE DE QUALIDADE: INVALIDADO</b>

Erro na mensagem. Esta deve ser modificada para: “Crédito no valor XX para a poupança YY foi realizado com sucesso”.

**Comment by wendellpbarreto** [comment]
<b>DOCUMENTAÇÃO</b>

Prazo: 2 dias

*documentação*

Desenvolvedor: @adelinosegundo

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO DO COMITÊ DE CONTROLE DE MUDANÇAS: VALIDADO</b>

**Comment by wendellpbarreto** [comment]
<b> RESULTADO DA ACEITAÇÃO DO CLIENTE: ACEITO</b>

Interessados: Cliente C
