### ISSUE TITLE
Criar testes unitarios

### ISSUE THREAD

**Issue by adelinosegundo** [adelinosegundo/gcm-bank#12]
Criar testes unitarios para as funcionalidades de credito e debito

**Comment by rafaelfqueiroz** [comment]
**RESULTADO DA VALIDAÇÃO: VALIDADO**

Prioridade resultante: Média
Impacto: Médio

**Comment by rafaelfqueiroz** [comment]
**RESULTADO DA VALIDAÇÃO DA EQUIPE DE CONTROLE DE MUDANÇAS: VALIDADO**

**Comment by rafaelfqueiroz** [comment]
**DOCUMENTAÇÃO**

Prazo: 30 dias

documentação

Desenvolvedor: @adelinosegundo

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO DO CONTROLE DE QUALIDADE: VALIDADO</b>
