### ISSUE TITLE
Métricas de código

### ISSUE THREAD

**Issue by rafaelfqueiroz** [adelinosegundo/gcm-bank#15]
Elaborar relatório com as métricas de código.

**Comment by rafaelfqueiroz** [comment]
**RESULTADO DA VALIDAÇÃO: VALIDADO**

Prioridade resultante: Média
Impacto: Média

**Comment by rafaelfqueiroz** [comment]
**RESULTADO DA VALIDAÇÃO DA EQUIPE DE CONTROLE DE MUDANÇAS: VALIDADO**

**Comment by rafaelfqueiroz** [comment]
**DOCUMENTAÇÃO**

Prazo: 15 dias

documentação

Desenvolvedor: @adelinosegundo

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO DO CONTROLE DE QUALIDADE: VALIDADO</b>
