### ISSUE TITLE
Restrição de commit

### ISSUE THREAD

**Issue by rafaelfqueiroz** [adelinosegundo/gcm-bank#16]
Realizar configuração para restringir os commits.

**Comment by rafaelfqueiroz** [comment]
**RESULTADO DA VALIDAÇÃO: VALIDADO**

Prioridade resultante: Média
Impacto: Médio

**Comment by rafaelfqueiroz** [comment]
**RESULTADO DA VALIDAÇÃO DA EQUIPE DE CONTROLE DE MUDANÇAS: VALIDADO**

**Comment by rafaelfqueiroz** [comment]
DOCUMENTAÇÃO

Prazo: 10 dias

documentação

Desenvolvedor: @adelinosegundo

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO DO CONTROLE DE QUALIDADE: VALIDADO</b>
