### ISSUE TITLE
Cenário 1 - Solicitação de mudança da regra de débito

### ISSUE THREAD

**Issue by adelinosegundo** [adelinosegundo/gcm-bank#6]
O saldo mínimo em conta deverá ser R$ 2,00. Esta restrição deve ser informada ao usuário através de mensagem caso o valor a ser debitado ultrapasse o saldo mínimo em conta.

<b>Solicitado por: Cliente 1</b>

**Comment by wendellpbarreto** [comment]
Mudança está em análise.

**Comment by wendellpbarreto** [comment]
Mudança validada e atribuída prioridade média.

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO: VALIDADO</b>

Prioridade resultante: Média
Impacto: Baixo

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO: VALIDADO</b>

Prioridade resultante: Média
Impacto: Baixo

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO DO COMITÊ DE CONTROLE DE MUDANÇAS: VALIDADO</b>

**Comment by wendellpbarreto** [comment]
<b>DOCUMENTAÇÃO</b>

Prazo: 15 dias

<documentação>

Desenvolvedor: @adelinosegundo

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO DO CONTROLE DE QUALIDADE: VALIDADO</b>

**Comment by wendellpbarreto** [comment]
<b> RESULTADO DA ACEITAÇÃO DO CLIENTE: ACEITO</b>

Interessados: Cliente 1
