### ISSUE TITLE
Cenário 2 - [X001] Alteração na operação de crédito  

### ISSUE THREAD

**Issue by adelinosegundo** [adelinosegundo/gcm-bank#7]
Alteração na operação de crédito para que seja informada uma descrição para a operação.

<b>Solicitado por: Cliente X</b>

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO: VALIDADO</b>

Prioridade resultante: Alta
Impacto: Médio

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO DO COMITÊ DE CONTROLE DE MUDANÇAS: VALIDADO</b>

**Comment by wendellpbarreto** [comment]
<b>DOCUMENTAÇÃO</b>

Prazo: 5 dias

*documentação*

Desenvolvedor: @adelinosegundo

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO DO CONTROLE DE QUALIDADE: VALIDADO</b>

**Comment by wendellpbarreto** [comment]
<b> RESULTADO DA ACEITAÇÃO DO CLIENTE: ACEITO</b>

Interessados: Cliente X
