### ISSUE TITLE
Cenário 2 - [Y001] Alteração na operação de débito  

### ISSUE THREAD

**Issue by adelinosegundo** [adelinosegundo/gcm-bank#8]
Alteração na operação de débito seja informada uma descrição para a operação.

Solicitado por: Cliente Y

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO: VALIDADO</b>

Prioridade resultante: Alta
Impacto: Alta

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO DO COMITÊ DE CONTROLE DE MUDANÇAS: VALIDADO</b>

**Comment by wendellpbarreto** [comment]
<b>DOCUMENTAÇÃO</b>

Prazo: 20 dias

*documentação*

Desenvolvedor: @adelinosegundo

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO DO CONTROLE DE QUALIDADE: VALIDADO</b>

**Comment by wendellpbarreto** [comment]
<b> RESULTADO DA ACEITAÇÃO DO CLIENTE: ACEITO</b>

Interessados: Cliente Y
