### ISSUE TITLE
Cenário 3 - Bug na funcionalidade de bônus

### ISSUE THREAD

**Issue by adelinosegundo** [adelinosegundo/gcm-bank#9]
O bônus deve ser de 3% do valor de cada operação.

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO: VALIDADO</b>

Prioridade resultante: Alta
Impacto: Baixo

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO DO COMITÊ DE CONTROLE DE MUDANÇAS: VALIDADO</b>

**Comment by wendellpbarreto** [comment]
<b>DOCUMENTAÇÃO</b>

Prazo: 1 dia

*documentação*

Desenvolvedor: @adelinosegundo

**Comment by wendellpbarreto** [comment]
<b>RESULTADO DA VALIDAÇÃO DO CONTROLE DE QUALIDADE: VALIDADO</b>

**Comment by wendellpbarreto** [comment]
<b> RESULTADO DA ACEITAÇÃO DO CLIENTE: ACEITO</b>

Interessados: Cliente 1
